baseurl = "http://ben.kulbertis.org"
languageCode = "en-us"
title = "Ben Kulbertis"

[permalinks]
  post = "/:year/:month/:filename"

[params]
    Description = "Deployment Automation Engineer and Systems Administrator"
    MetaDescription = "Hey! I'm Ben. I'm a deployment automation engineer living in Salt Lake City, Utah."
    Location = "Salt Lake City, Utah, USA"
    [params.authors]
      [params.authors.Ben]
        "firstName" = "Ben"
        "lastName" = "Kulbertis"
