baseurl = "http://ben.kulbertis.org"
languageCode = "en-us"
title = "Ben Kulbertis"

[permalinks]
  post = "/:year/:month/:filename"

[params]
    Description = "Software Dev / Ops Automation"
    MetaDescription = "Hey! I'm Ben. I automate video operations at Amazon IVS/Twitch in Irvine, California."
    Location = "Irvine, California, USA"
    [params.authors]
      [params.authors.Ben]
        "firstName" = "Ben"
        "lastName" = "Kulbertis"
