baseurl = "http://ben.kulbertis.org"
languageCode = "en-us"
title = "Ben Kulbertis"

[permalinks]
  post = "/:year/:month/:filename"

[params]
    Description = "Full Stack Web Developer and Technology Enthusiast"
    MetaDescription = "Hey! I'm Ben. I'm a young web developer living in Salt Lake City, Utah. I'm currently interesting in writing web applications using Ember.js and Ruby on Rails."
    Location = "Salt Lake City, Utah, USA"
    [params.authors]
      [params.authors.Ben]
        "firstName" = "Ben"
        "lastName" = "Kulbertis"
